name: Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Go CI lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false"