name: Security

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Guard:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: -exclude-dir=internal/*/ ./...
  Security:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Install Go vuln check
        run: |
          export GO111MODULE=on
          export PATH=${PATH}:`go env GOPATH`/bin
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run Go vuln check
        run: "`go env GOPATH`/bin/govulncheck ./..."